@echo off
setlocal enabledelayedexpansion
title MAC Worker PC Setup — MBM University

echo.
echo  ============================================================
echo   MAC — MBM AI Cloud  ^|  Worker Node Setup
echo   MBM University, Jodhpur
echo  ============================================================
echo.

docker version >nul 2>&1
if errorlevel 1 (
    echo  [ERROR] Docker not running. Start Docker Desktop first.
    pause & exit /b 1
)
echo  [OK] Docker is running.

nvidia-smi >nul 2>&1
if errorlevel 1 (
    echo  [WARN] No NVIDIA GPU detected. Worker requires GPU for model inference.
) else (
    echo  [OK] NVIDIA GPU detected.
)

echo.
echo  Enter setup details:
echo  -------------------------------------------------------
set /p HOST_URL= HOST URL (e.g. http://10.10.12.115):
if "!HOST_URL!"=="" ( echo [ERROR] Required. & pause & exit /b 1 )

echo.
echo  Get an enrollment token: !HOST_URL!/admin - Cluster - New Enrollment Token
echo.
set /p ENROLL_TOKEN= Enrollment Token:
if "!ENROLL_TOKEN!"=="" ( echo [ERROR] Required. & pause & exit /b 1 )

set /p WORKER_NAME= Worker Name [worker-lab-1]:
if "!WORKER_NAME!"=="" set WORKER_NAME=worker-lab-1

echo.
echo  Choose model for this GPU:
echo    1  Gemma 3 4B AWQ     (~4 GB, recommended)
echo    2  Qwen 2.5 7B AWQ    (~5 GB, best general)
echo    3  Mistral 7B AWQ     (~4.5 GB, multilingual)
echo    4  DeepSeek R1 7B AWQ (~5 GB, reasoning/math)
echo    5  Custom model
echo.
set /p MODEL_CHOICE= Choose [1]:
if "!MODEL_CHOICE!"=="" set MODEL_CHOICE=1

set VLLM_MAX_LEN=8192
if "!MODEL_CHOICE!"=="1" ( set VLLM_MODEL=mlabonne/gemma-3-4b-it-AWQ & set VLLM_SERVED_NAME=gemma-3-4b )
if "!MODEL_CHOICE!"=="2" ( set VLLM_MODEL=Qwen/Qwen2.5-7B-Instruct-AWQ & set VLLM_SERVED_NAME=qwen2.5-7b )
if "!MODEL_CHOICE!"=="3" ( set VLLM_MODEL=solidrust/Mistral-7B-Instruct-v0.3-AWQ & set VLLM_SERVED_NAME=mistral-7b )
if "!MODEL_CHOICE!"=="4" ( set VLLM_MODEL=deepseek-ai/DeepSeek-R1-Distill-Qwen-7B & set VLLM_SERVED_NAME=deepseek-r1-7b )
if "!MODEL_CHOICE!"=="5" (
    set /p VLLM_MODEL= HuggingFace model ID:
    set /p VLLM_SERVED_NAME= Served name:
)

set /p HF_TOKEN= HuggingFace Token (blank if not needed):
set /p GPU_MEM= GPU memory utilization [0.85]:
if "!GPU_MEM!"=="" set GPU_MEM=0.85

echo.
echo  Writing .env.worker...
(
    echo # Generated by setup-worker.bat on %date%
    echo MAC_MASTER_URL=!HOST_URL!
    echo MAC_ENROLL_TOKEN=!ENROLL_TOKEN!
    echo MAC_WORKER_NAME=!WORKER_NAME!
    echo MAC_WORKER_IP=
    echo VLLM_MODEL=!VLLM_MODEL!
    echo VLLM_SERVED_NAME=!VLLM_SERVED_NAME!
    echo VLLM_GPU_MEM=!GPU_MEM!
    echo VLLM_MAX_LEN=!VLLM_MAX_LEN!
    echo VLLM_DTYPE=auto
    echo VLLM_PORT=8001
    echo HF_TOKEN=!HF_TOKEN!
    echo TRANSFORMERS_OFFLINE=0
) > .env.worker
echo  [OK] .env.worker saved.

echo.
echo  Pulling images (first run may take a few minutes)...
docker compose -f docker-compose.worker.yml --env-file .env.worker pull

echo.
echo  Starting worker services...
docker compose -f docker-compose.worker.yml --env-file .env.worker up -d
if errorlevel 1 ( echo. & echo [ERROR] Failed to start. Check Docker Desktop. & pause & exit /b 1 )

echo.
echo  ============================================================
echo   Worker is starting!
echo.
echo   Model download: 10-30 min first run.
echo   Monitor:  docker logs -f mac-worker-vllm
echo.
echo   Next:  Open !HOST_URL!/admin
echo          Go to Cluster panel
echo          Approve "!WORKER_NAME!" when it appears (pending)
echo.
echo   This PC will then serve: !VLLM_SERVED_NAME!
echo  ============================================================
echo.
pause
