@echo off
setlocal enabledelayedexpansion
title MAC MOST — PC2 WORKER (Mistral-7B Creative/Chat LLM)
cd /d "%~dp0"

echo.
echo  ================================================================
echo   MAC MOST — MBM AI Cloud
echo   PC2: WORKER NODE — Mistral-7B-Instruct-v0.3-AWQ
echo   Role: Creative writing, general chat, essays, language tasks
echo   MBM University, Jodhpur, Rajasthan, India
echo  ================================================================
echo.

REM ──────────────────────────────────────────────────────────────────────────────
REM STEP 1: Docker check
REM ──────────────────────────────────────────────────────────────────────────────
echo [1/9] Checking Docker...
docker info >nul 2>&1
if errorlevel 1 (
    where docker >nul 2>&1
    if errorlevel 1 (
        echo  [INFO] Installing Docker Desktop via winget...
        winget install -e --id Docker.DockerDesktop --accept-source-agreements --accept-package-agreements
        echo  [ACTION] RESTART this PC, then run start-most-worker-pc2.bat again.
        pause & exit /b 0
    )
    echo  Starting Docker Desktop...
    start "" "C:\Program Files\Docker\Docker\Docker Desktop.exe" 2>nul
    timeout /t 60 /nobreak >nul
    docker info >nul 2>&1
    if errorlevel 1 (echo  [ERROR] Docker not ready. & pause & exit /b 1)
)
echo  [OK] Docker is running.

REM ──────────────────────────────────────────────────────────────────────────────
REM STEP 2: Read cluster.env (host IP + enrollment token)
REM ──────────────────────────────────────────────────────────────────────────────
echo.
echo [2/9] Reading cluster configuration...
set "HOST_IP="
set "HOST_URL="
set "HOST_HTTPS_URL="
set "ENROLL_TOKEN="
set "ADMIN_ROLL=abhisek.cse@mbm.ac.in"
set "ADMIN_PASS=Admin@1234"

if exist "cluster.env" (
    echo  Found cluster.env — loading configuration...
    for /f "usebackq tokens=1,* delims==" %%a in ("cluster.env") do (
        if "%%a"=="HOST_IP"         set "HOST_IP=%%b"
        if "%%a"=="HOST_URL"        set "HOST_URL=%%b"
        if "%%a"=="HOST_HTTPS_URL"  set "HOST_HTTPS_URL=%%b"
        if "%%a"=="ENROLL_TOKEN"    set "ENROLL_TOKEN=%%b"
        if "%%a"=="ADMIN_ROLL"      set "ADMIN_ROLL=%%b"
        if "%%a"=="ADMIN_PASS"      set "ADMIN_PASS=%%b"
    )
    echo  [OK] Loaded: HOST_IP=!HOST_IP!
) else (
    echo  [WARN] cluster.env not found.
    echo         Copy cluster.env from the HOST PC (generated by start-most-host.bat).
    echo         OR enter the host details manually below.
    echo.
)

REM ── If HOST_IP still missing, ask ────────────────────────────────────────────
if not defined HOST_IP (
    echo  Enter HOST PC (PC1) LAN IP address (e.g. 10.10.12.115):
    set /p HOST_IP="Host IP: "
    if not defined HOST_IP (echo  [ERROR] Host IP required. & pause & exit /b 1)
)
if not defined HOST_URL     set "HOST_URL=http://!HOST_IP!"
if not defined HOST_HTTPS_URL set "HOST_HTTPS_URL=https://!HOST_IP!"

REM ── Use HTTPS URL for API calls (host has SSL) ───────────────────────────────
set "API_URL=!HOST_HTTPS_URL!"

REM ── If ENROLL_TOKEN missing, auto-fetch from host ─────────────────────────────
if not defined ENROLL_TOKEN (
    echo  Attempting to auto-fetch enrollment token from host...
    for /f "usebackq tokens=*" %%t in (`powershell -NoProfile -Command ^
        "[System.Net.ServicePointManager]::ServerCertificateValidationCallback = {$true}; " ^
        "try { " ^
            "$lr = Invoke-RestMethod -Uri '!API_URL!/api/v1/auth/login' -Method POST " ^
                "-Body (ConvertTo-Json @{roll_number='!ADMIN_ROLL!';password='!ADMIN_PASS!'}) " ^
                "-ContentType 'application/json' -ErrorAction Stop; " ^
            "$er = Invoke-RestMethod -Uri '!API_URL!/api/v1/cluster/enroll-token' -Method POST " ^
                "-Headers @{Authorization='Bearer '+$lr.access_token} " ^
                "-Body (ConvertTo-Json @{label='pc2-mistral';expires_hours=168}) " ^
                "-ContentType 'application/json' -ErrorAction Stop; " ^
            "Write-Output $er.token " ^
        "} catch { Write-Output 'TOKEN_ERROR' }" 2^>nul`) do set "ENROLL_TOKEN=%%t"

    if "!ENROLL_TOKEN!"=="TOKEN_ERROR" (
        echo  [WARN] Auto-fetch failed. Enter enrollment token manually.
        echo         From host: Login as Admin ^> Admin Panel ^> Cluster ^> Generate Token
        set /p ENROLL_TOKEN="Enrollment token: "
        if not defined ENROLL_TOKEN (echo  [ERROR] Token required. & pause & exit /b 1)
    ) else (
        echo  [OK] Enrollment token auto-fetched from host.
    )
)
echo  [OK] Host: !API_URL!

REM ──────────────────────────────────────────────────────────────────────────────
REM STEP 3: GPU Test
REM ──────────────────────────────────────────────────────────────────────────────
echo.
echo [3/9] GPU Test for Mistral-7B-AWQ (~5 GB VRAM needed)...
set "GPU_NAME=None"
set "GPU_VRAM_MB=0"
set "HAS_GPU=0"

nvidia-smi >nul 2>&1
if errorlevel 1 (
    echo  [ERROR] No NVIDIA GPU detected. Mistral-7B requires a GPU.
    echo          Install NVIDIA drivers from https://nvidia.com/drivers
    pause & exit /b 1
)

for /f "usebackq tokens=*" %%a in (`nvidia-smi --query-gpu=name --format=csv,noheader 2^>nul`) do (
    if "!HAS_GPU!"=="0" ( set "GPU_NAME=%%a" & set "HAS_GPU=1" )
)
for /f "usebackq tokens=*" %%a in (`nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits 2^>nul`) do (
    if "!GPU_VRAM_MB!"=="0" set /a "GPU_VRAM_MB=%%a"
)
set /a "GPU_VRAM_GB=!GPU_VRAM_MB! / 1024"
echo   GPU  : !GPU_NAME!
echo   VRAM : !GPU_VRAM_MB! MB (~!GPU_VRAM_GB! GB)

if !GPU_VRAM_MB! LSS 4500 (
    echo  [WARN] Low VRAM (!GPU_VRAM_MB! MB^). Mistral-7B-AWQ needs ~5 GB. May not load.
)

echo  Testing Docker GPU passthrough...
docker run --rm --gpus all nvidia/cuda:12.1.0-base-ubuntu22.04 nvidia-smi --query-gpu=name --format=csv,noheader >nul 2>&1
if errorlevel 1 (
    echo.
    echo  [ERROR] Docker cannot access the GPU.
    echo   FIX 1: Docker Desktop ^> Settings ^> General ^> Use WSL 2 backend (ON)
    echo   FIX 2: Docker Desktop ^> Settings ^> Resources ^> WSL Integration ^> Enable GPU
    echo   FIX 3: Apply and Restart Docker Desktop, then rerun this script.
    pause & exit /b 1
)
echo  [OK] GPU accessible inside Docker.

REM ──────────────────────────────────────────────────────────────────────────────
REM STEP 4: Detect this PC's LAN IP
REM ──────────────────────────────────────────────────────────────────────────────
echo.
echo [4/9] Detecting this PC's LAN IP...
set "WORKER_IP="
for /f "usebackq tokens=*" %%i in (`powershell -NoProfile -Command "(Get-NetIPAddress -AddressFamily IPv4 | Where-Object { $_.InterfaceAlias -notmatch 'Loopback|vEthernet|WSL|Docker|Hyper-V' -and $_.IPAddress -ne '127.0.0.1' } | Sort-Object -Property InterfaceMetric | Select-Object -First 1).IPAddress" 2^>nul`) do set "WORKER_IP=%%i"
if not defined WORKER_IP set "WORKER_IP=0.0.0.0"
echo  [OK] This PC's LAN IP: !WORKER_IP!
set "WORKER_NAME=%COMPUTERNAME%-Mistral-PC2"
echo  [OK] Worker name: !WORKER_NAME!

REM ──────────────────────────────────────────────────────────────────────────────
REM STEP 5: Firewall
REM ──────────────────────────────────────────────────────────────────────────────
echo.
echo [5/9] Firewall rules...
netsh advfirewall firewall delete rule name="MAC-MOST Worker vLLM" >nul 2>&1
netsh advfirewall firewall add rule name="MAC-MOST Worker vLLM" dir=in action=allow protocol=TCP localport=8001 profile=any >nul 2>&1
echo  [OK] Port 8001 opened for vLLM.

REM ──────────────────────────────────────────────────────────────────────────────
REM STEP 6: Select model based on VRAM
REM ──────────────────────────────────────────────────────────────────────────────
echo.
echo [6/9] Selecting Mistral model based on GPU VRAM...

REM Default: AWQ (4-bit), ~5 GB VRAM — works on 6 GB+ GPUs
set "VLLM_MODEL=solidrust/Mistral-7B-Instruct-v0.3-AWQ"
set "VLLM_GPU_MEM=0.85"
set "VLLM_MAX_LEN=8192"
set "VLLM_DTYPE=auto"
set "MODEL_LABEL=Mistral-7B-v0.3-AWQ (4-bit ~5GB)"
set "DOWNLOAD_SIZE=~4.5 GB"

REM 8+ GB VRAM: upgrade to full fp16 — better quality, more VRAM
if !GPU_VRAM_MB! GEQ 8000 (
    set "VLLM_MODEL=mistralai/Mistral-7B-Instruct-v0.3"
    set "VLLM_GPU_MEM=0.88"
    set "VLLM_MAX_LEN=8192"
    set "VLLM_DTYPE=float16"
    set "MODEL_LABEL=Mistral-7B-v0.3-fp16 (16-bit ~14GB)"
    set "DOWNLOAD_SIZE=~14 GB"
    echo  [INFO] 8+ GB VRAM — using full fp16 Mistral-7B-v0.3 for better quality.
) else (
    echo  [INFO] Using AWQ 4-bit Mistral-7B-v0.3 (fits in 6 GB VRAM).
)
echo  Model    : !MODEL_LABEL!
echo  Download : !DOWNLOAD_SIZE! (first run only — cached after that)

REM ──────────────────────────────────────────────────────────────────────────────
REM STEP 7: Write .env.worker
REM ──────────────────────────────────────────────────────────────────────────────
echo.
echo [7/9] Writing .env.worker configuration...
(
    echo MAC_MASTER_URL=!HOST_HTTPS_URL!
    echo MAC_ENROLL_TOKEN=!ENROLL_TOKEN!
    echo MAC_WORKER_NAME=!WORKER_NAME!
    echo MAC_WORKER_IP=!WORKER_IP!
    echo MAC_VLLM_PORT=8001
    echo MAC_VLLM_MODEL=!VLLM_MODEL!
    echo MAC_HEARTBEAT_SEC=10
    echo MAC_ENGINE=vllm
    echo MAC_GPU_NAME=!GPU_NAME!
    echo MAC_GPU_VRAM_MB=!GPU_VRAM_MB!
    echo VLLM_PORT=8001
    echo VLLM_MODEL=!VLLM_MODEL!
    echo VLLM_GPU_MEM=!VLLM_GPU_MEM!
    echo VLLM_MAX_LEN=!VLLM_MAX_LEN!
    echo VLLM_DTYPE=!VLLM_DTYPE!
    echo VLLM_SERVED_NAME=!VLLM_MODEL!
) > .env.worker
echo  [OK] .env.worker saved.

REM ──────────────────────────────────────────────────────────────────────────────
REM STEP 8: Start vLLM Docker container
REM   - First run: HuggingFace downloads the model weights (!DOWNLOAD_SIZE!)
REM   - Subsequent starts: loads from local cache (~2-3 min)
REM   - HF_TOKEN optional — Mistral-7B is public, no token needed
REM ──────────────────────────────────────────────────────────────────────────────
echo.
echo [8/9] Starting Mistral vLLM container...
echo  Model: !VLLM_MODEL!
echo  NOTE: First run downloads !DOWNLOAD_SIZE! from HuggingFace.
echo        Keep internet ON during first start. This only happens once.
echo.

docker compose -f docker-compose.worker.yml --env-file .env.worker up -d --remove-orphans
if errorlevel 1 (
    echo  [ERROR] Docker Compose failed.
    echo   Check logs: docker compose -f docker-compose.worker.yml logs --tail 50
    pause & exit /b 1
)
echo  [OK] vLLM container started.
echo.
echo  Waiting for vLLM to load model (first run: 5-15 min for download + load)...
echo  Tip: Open another terminal and run:
echo       docker logs mac-worker-vllm -f
echo  to watch the download progress.
echo.

REM Wait for vLLM health before registering with host
set "VLLM_READY=0"
set "WAIT_COUNT=0"
:wait_vllm
timeout /t 15 /nobreak >nul
set /a "WAIT_COUNT+=1"
for /f "usebackq tokens=*" %%h in (`curl -sf http://localhost:8001/health 2^>nul`) do (
    set "VLLM_READY=1"
)
if "!VLLM_READY!"=="1" (
    echo  [OK] vLLM is ready! Model loaded on GPU.
    goto vllm_ok
)
set /a "WAITED=!WAIT_COUNT! * 15"
echo  Still loading... (!WAITED!s elapsed) — model loading into GPU VRAM
if !WAIT_COUNT! LSS 60 goto wait_vllm
echo  [WARN] vLLM not ready after 15 min. Proceeding anyway — agent will retry.
:vllm_ok

REM Show loaded model
for /f "usebackq tokens=*" %%m in (`curl -s http://localhost:8001/v1/models 2^>nul`) do (
    echo  vLLM serving: %%m
)

REM ──────────────────────────────────────────────────────────────────────────────
REM STEP 9: Check Python + start worker agent
REM ──────────────────────────────────────────────────────────────────────────────
echo.
echo [9/9] Starting worker agent...
python --version >nul 2>&1
if errorlevel 1 (
    echo  [INFO] Python not found. Installing Python 3.11...
    winget install -e --id Python.Python.3.11 --accept-source-agreements --accept-package-agreements
    echo  [ACTION] RESTART this PC, then run start-most-worker-pc2.bat again.
    pause & exit /b 0
)
python -c "import psutil, requests" >nul 2>&1
if errorlevel 1 (
    echo  Installing required Python packages...
    python -m pip install psutil requests -q
)

set "MAC_MASTER_URL=!HOST_HTTPS_URL!"
set "MAC_ENROLL_TOKEN=!ENROLL_TOKEN!"
set "MAC_WORKER_NAME=!WORKER_NAME!"
set "MAC_WORKER_IP=!WORKER_IP!"
set "MAC_VLLM_PORT=8001"
set "MAC_VLLM_MODEL=!VLLM_MODEL!"
set "MAC_GPU_NAME=!GPU_NAME!"
set "MAC_GPU_VRAM_MB=!GPU_VRAM_MB!"
set "MAC_HEARTBEAT_SEC=10"
set "MAC_ENGINE=vllm"

echo.
echo  ================================================================
echo   PC2 WORKER IS RUNNING
echo.
echo   Model    : !MODEL_LABEL!
echo   This PC  : !WORKER_IP!:8001
echo   Host     : !HOST_HTTPS_URL!
echo.
echo   ── NEXT STEPS ──────────────────────────────────────────────
echo   1. Open !HOST_HTTPS_URL! in browser on ANY PC on the LAN
echo   2. Login as Admin: abhisek.cse@mbm.ac.in / Admin@1234
echo   3. Admin Panel ^> Cluster ^> Nodes
echo   4. Find "!WORKER_NAME!" → Click APPROVE
echo   5. Mistral-7B appears in the chat model dropdown!
echo.
echo   Worker auto-deregisters when this window is closed.
echo   vLLM log: docker compose -f docker-compose.worker.yml logs -f
echo  ================================================================
echo.

python worker_agent.py
pause
