@echo off
setlocal enabledelayedexpansion
title MAC MOST — PC3 WORKER (Vision AI — Image Analysis + Qwen2-VL)
cd /d "%~dp0"

echo.
echo  ================================================================
echo   MAC MOST — MBM AI Cloud
echo   PC3: WORKER NODE — Vision AI (Qwen2-VL-7B)
echo   Role: Image Q^&A, document analysis, visual reasoning,
echo         diagram explanation, copy-check scanning
echo   MBM University, Jodhpur, Rajasthan, India
echo  ================================================================
echo.

REM ──────────────────────────────────────────────────────────────────────────────
REM STEP 1: Docker
REM ──────────────────────────────────────────────────────────────────────────────
echo [1/9] Checking Docker...
docker info >nul 2>&1
if errorlevel 1 (
    where docker >nul 2>&1
    if errorlevel 1 (
        echo  [INFO] Installing Docker Desktop via winget...
        winget install -e --id Docker.DockerDesktop --accept-source-agreements --accept-package-agreements
        echo  [ACTION] RESTART this PC, then run start-most-worker-pc3.bat again.
        pause & exit /b 0
    )
    echo  Starting Docker Desktop...
    start "" "C:\Program Files\Docker\Docker\Docker Desktop.exe" 2>nul
    timeout /t 60 /nobreak >nul
    docker info >nul 2>&1
    if errorlevel 1 (echo  [ERROR] Docker not ready. & pause & exit /b 1)
)
echo  [OK] Docker is running.

REM ──────────────────────────────────────────────────────────────────────────────
REM STEP 2: Read cluster.env (host IP + enrollment token)
REM ──────────────────────────────────────────────────────────────────────────────
echo.
echo [2/9] Reading cluster configuration...
set "HOST_IP="
set "HOST_URL="
set "ENROLL_TOKEN="
set "ADMIN_EMAIL=abhisek.cse@mbm.ac.in"
set "ADMIN_PASS=Admin@1234"

if exist "cluster.env" (
    echo  Found cluster.env — loading configuration...
    for /f "usebackq tokens=1,* delims==" %%a in ("cluster.env") do (
        if "%%a"=="HOST_IP"      set "HOST_IP=%%b"
        if "%%a"=="HOST_URL"     set "HOST_URL=%%b"
        if "%%a"=="ENROLL_TOKEN" set "ENROLL_TOKEN=%%b"
        if "%%a"=="ADMIN_EMAIL"  set "ADMIN_EMAIL=%%b"
        if "%%a"=="ADMIN_PASS"   set "ADMIN_PASS=%%b"
    )
    echo  [OK] Loaded: HOST_IP=!HOST_IP!
) else (
    echo  [WARN] cluster.env not found.
    echo         Copy cluster.env from the HOST PC (generated by start-most-host.bat).
    echo         OR enter the host details manually below.
    echo.
)

REM ── If HOST_IP still missing, ask once ───────────────────────────────────────
if not defined HOST_IP (
    echo  Enter HOST PC (PC1) LAN IP address:
    echo  Example: 192.168.1.100
    echo.
    set /p HOST_IP="Host IP: "
    if not defined HOST_IP (echo  [ERROR] Host IP required. & pause & exit /b 1)
    set "HOST_URL=http://!HOST_IP!"
)
if not defined HOST_URL set "HOST_URL=http://!HOST_IP!"

REM ── If ENROLL_TOKEN missing, auto-fetch from host ─────────────────────────────
if not defined ENROLL_TOKEN (
    echo  Attempting to fetch enrollment token from host...
    for /f "usebackq tokens=*" %%t in (`powershell -NoProfile -Command ^
        "try { " ^
            "$lr=Invoke-RestMethod -Uri '!HOST_URL!/api/v1/auth/login' -Method POST " ^
                "-Body ([pscustomobject]@{email='!ADMIN_EMAIL!';password='!ADMIN_PASS!'} | ConvertTo-Json) " ^
                "-ContentType 'application/json' -ErrorAction Stop; " ^
            "$er=Invoke-RestMethod -Uri '!HOST_URL!/api/v1/cluster/enroll-token' -Method POST " ^
                "-Headers @{Authorization='Bearer '+$lr.access_token} " ^
                "-Body ([pscustomobject]@{label='pc3-vision';expires_hours=168} | ConvertTo-Json) " ^
                "-ContentType 'application/json' -ErrorAction Stop; " ^
            "Write-Output $er.token " ^
        "} catch { Write-Output 'TOKEN_ERROR' }" 2^>nul`) do set "ENROLL_TOKEN=%%t"

    if "!ENROLL_TOKEN!"=="TOKEN_ERROR" (
        echo  [WARN] Auto-fetch failed. Enter enrollment token manually.
        echo         From host: Admin Panel ^> Cluster ^> Generate Token
        set /p ENROLL_TOKEN="Enrollment token: "
        if not defined ENROLL_TOKEN (echo  [ERROR] Token required. & pause & exit /b 1)
    ) else (
        echo  [OK] Enrollment token fetched from host.
    )
)
echo  [OK] Host: !HOST_URL!

REM ──────────────────────────────────────────────────────────────────────────────
REM STEP 3: GPU Test
REM ──────────────────────────────────────────────────────────────────────────────
echo.
echo [3/9] GPU Test for Vision AI (~8 GB VRAM recommended)...
set "GPU_NAME=None"
set "GPU_VRAM_MB=0"
set "HAS_GPU=0"

nvidia-smi >nul 2>&1
if errorlevel 1 (
    echo  [ERROR] No NVIDIA GPU detected. Vision AI requires a GPU.
    pause & exit /b 1
)

for /f "usebackq tokens=*" %%a in (`nvidia-smi --query-gpu=name --format=csv,noheader 2^>nul`) do (
    if "!HAS_GPU!"=="0" ( set "GPU_NAME=%%a" & set "HAS_GPU=1" )
)
for /f "usebackq tokens=*" %%a in (`nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits 2^>nul`) do (
    if "!GPU_VRAM_MB!"=="0" set /a "GPU_VRAM_MB=%%a"
)
set /a "GPU_VRAM_GB=!GPU_VRAM_MB! / 1024"
echo   GPU  : !GPU_NAME!
echo   VRAM : !GPU_VRAM_MB! MB (~!GPU_VRAM_GB! GB)

echo  Testing Docker GPU passthrough...
docker run --rm --gpus all nvidia/cuda:12.1.0-base-ubuntu22.04 nvidia-smi --query-gpu=name --format=csv,noheader >nul 2>&1
if errorlevel 1 (
    echo.
    echo  [ERROR] Docker cannot access the GPU.
    echo   FIX: Docker Desktop ^> Settings ^> General ^> Use WSL 2 engine (ON)
    echo        Docker Desktop ^> Settings ^> Resources ^> WSL Integration ^> GPU (ON)
    echo        Apply and Restart, then rerun this script.
    pause & exit /b 1
)
echo  [OK] GPU accessible inside Docker.

REM ──────────────────────────────────────────────────────────────────────────────
REM STEP 4: Detect this PC's LAN IP
REM ──────────────────────────────────────────────────────────────────────────────
echo.
echo [4/9] Detecting this PC's LAN IP...
set "WORKER_IP="
for /f "usebackq tokens=*" %%i in (`powershell -NoProfile -Command "(Get-NetIPAddress -AddressFamily IPv4 | Where-Object { $_.InterfaceAlias -notmatch 'Loopback|vEthernet|WSL|Docker|Hyper-V' -and $_.IPAddress -ne '127.0.0.1' } | Sort-Object -Property InterfaceMetric | Select-Object -First 1).IPAddress" 2^>nul`) do set "WORKER_IP=%%i"
if not defined WORKER_IP set "WORKER_IP=0.0.0.0"
echo  [OK] This PC's LAN IP: !WORKER_IP!

set "WORKER_NAME=%COMPUTERNAME%-Vision-PC3"
echo  [OK] Worker name: !WORKER_NAME!

REM ──────────────────────────────────────────────────────────────────────────────
REM STEP 5: Firewall
REM ──────────────────────────────────────────────────────────────────────────────
echo.
echo [5/9] Firewall rules...
netsh advfirewall firewall delete rule name="MAC-MOST Worker vLLM" >nul 2>&1
netsh advfirewall firewall add rule name="MAC-MOST Worker vLLM" dir=in action=allow protocol=TCP localport=8001 profile=any >nul 2>&1
echo  [OK] Port 8001 opened for vLLM.

REM ──────────────────────────────────────────────────────────────────────────────
REM STEP 6: Select vision model based on VRAM
REM ──────────────────────────────────────────────────────────────────────────────
echo.
echo [6/9] Selecting vision model for !GPU_VRAM_MB! MB VRAM...

if !GPU_VRAM_MB! GEQ 7500 (
    REM 8+ GB: use Qwen2-VL-7B (best accuracy)
    set "VLLM_MODEL=Qwen/Qwen2-VL-7B-Instruct"
    set "VLLM_GPU_MEM=0.85"
    set "VLLM_MAX_LEN=4096"
    set "VLLM_DTYPE=bfloat16"
    set "MODEL_LABEL=Qwen2-VL-7B (Best Vision)"
) else if !GPU_VRAM_MB! GEQ 3500 (
    REM 4-7 GB: use Qwen2-VL-2B
    set "VLLM_MODEL=Qwen/Qwen2-VL-2B-Instruct"
    set "VLLM_GPU_MEM=0.82"
    set "VLLM_MAX_LEN=4096"
    set "VLLM_DTYPE=bfloat16"
    set "MODEL_LABEL=Qwen2-VL-2B (Light Vision)"
) else (
    REM < 4 GB: use Moondream2 (tiny but works)
    set "VLLM_MODEL=vikhyatk/moondream2"
    set "VLLM_GPU_MEM=0.75"
    set "VLLM_MAX_LEN=2048"
    set "VLLM_DTYPE=float16"
    set "MODEL_LABEL=Moondream2 (Lightweight Vision)"
)
echo  [OK] Selected: !MODEL_LABEL!

REM ──────────────────────────────────────────────────────────────────────────────
REM STEP 7: Write .env.worker and start vLLM
REM ──────────────────────────────────────────────────────────────────────────────
echo.
echo [7/9] Writing .env.worker and starting vLLM container...
(
    echo MAC_MASTER_URL=!HOST_URL!
    echo MAC_ENROLL_TOKEN=!ENROLL_TOKEN!
    echo MAC_WORKER_NAME=!WORKER_NAME!
    echo MAC_WORKER_IP=!WORKER_IP!
    echo MAC_VLLM_PORT=8001
    echo MAC_HEARTBEAT_SEC=10
    echo MAC_ENGINE=vllm
    echo MAC_GPU_NAME=!GPU_NAME!
    echo MAC_GPU_VRAM_MB=!GPU_VRAM_MB!
    echo VLLM_PORT=8001
    echo VLLM_MODEL=!VLLM_MODEL!
    echo MAC_VLLM_MODEL=!VLLM_MODEL!
    echo VLLM_GPU_MEM=!VLLM_GPU_MEM!
    echo VLLM_MAX_LEN=!VLLM_MAX_LEN!
    echo VLLM_DTYPE=!VLLM_DTYPE!
    echo VLLM_SERVED_NAME=!VLLM_MODEL!
) > .env.worker

docker compose -f docker-compose.worker.yml --env-file .env.worker up -d --remove-orphans
if errorlevel 1 (
    echo  [ERROR] Docker Compose failed.
    pause & exit /b 1
)
echo  [OK] vLLM container started (!MODEL_LABEL!).
echo   First run: model download varies 2-16 GB — keep internet on.
echo   Subsequent starts: ~2-4 min to load.

REM ──────────────────────────────────────────────────────────────────────────────
REM STEP 8: Check Python
REM ──────────────────────────────────────────────────────────────────────────────
echo.
echo [8/9] Checking Python...
python --version >nul 2>&1
if errorlevel 1 (
    echo  [INFO] Installing Python 3.11...
    winget install -e --id Python.Python.3.11 --accept-source-agreements --accept-package-agreements
    echo  [ACTION] RESTART this PC, then run start-most-worker-pc3.bat again.
    pause & exit /b 0
)
python -c "import psutil, requests" >nul 2>&1
if errorlevel 1 python -m pip install psutil requests -q
echo  [OK] Python ready.

REM ──────────────────────────────────────────────────────────────────────────────
REM STEP 9: Start worker agent
REM ──────────────────────────────────────────────────────────────────────────────
echo.
echo [9/9] Starting worker agent...

set "MAC_MASTER_URL=!HOST_URL!"
set "MAC_ENROLL_TOKEN=!ENROLL_TOKEN!"
set "MAC_WORKER_NAME=!WORKER_NAME!"
set "MAC_WORKER_IP=!WORKER_IP!"
set "MAC_VLLM_PORT=8001"
set "MAC_VLLM_MODEL=!VLLM_MODEL!"
set "MAC_GPU_NAME=!GPU_NAME!"
set "MAC_GPU_VRAM_MB=!GPU_VRAM_MB!"
set "MAC_HEARTBEAT_SEC=10"
set "MAC_ENGINE=vllm"

echo.
echo  ================================================================
echo   PC3 VISION WORKER RUNNING — !MODEL_LABEL!
echo.
echo   Host     : !HOST_URL!
echo   This PC  : !WORKER_IP!
echo   Model    : !MODEL_LABEL! (port 8001)
echo.
echo   NEXT STEPS:
echo   1. Open !HOST_URL! in browser on any PC
echo   2. Login as Admin: abhisek.cse@mbm.ac.in / Admin@1234
echo   3. Admin Panel ^> Cluster ^> Nodes
echo   4. Find "!WORKER_NAME!" and click Approve
echo   5. Vision model appears in Chat (use image upload button)
echo.
echo   This PC handles: image Q^&A, document scanning, visual chat,
echo                    diagram explanation, copy-check (vision).
echo.
echo   vLLM log: docker compose -f docker-compose.worker.yml logs -f
echo   This window = live agent log. Keep it open.
echo  ================================================================
echo.

python worker_agent.py
pause
